name: Send Webhook on Commit

on:
  push:
    branches:
      - main  # Branche cible

jobs:
  sendWebhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq -y
      - name: Make send_webhook.sh executable
        run: chmod +x ./send_webhook.sh
      - name: Send Webhook
        run: ./send_webhook.sh